<a href="https://colab.research.google.com/github/nitinfaye/Artificial-Neural-Network-ANN-./blob/main/loan_prediction_using_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#*Artificial Neural Network*

*inport laibraries*

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.5.0'

#Data preprocessing
importing dataset

In [3]:
data =pd.read_csv('/content/CHURN_~1.CSV')
X= data.iloc[:, 3:-1].values
y =data.iloc[:, -1].values

In [4]:
data.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


**encoding categorial data**

Lable Encoding the 'Genter'colomuns

In [7]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
X[:, 2] =le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding Geograpy coloumns

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
oc = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(oc.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splititng the dataset into the Trainig set and Iest set

Featuring Scalling

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2,random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

training ANN module

In [13]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

Compilling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5630 - accuracy: 0.7349
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4579 - accuracy: 0.8056
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4305 - accuracy: 0.8140
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4188 - accuracy: 0.8175
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4115 - accuracy: 0.8215
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4049 - accuracy: 0.8206
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3978 - accuracy: 0.8231
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3911 - accuracy: 0.8255
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3848 - accuracy: 0.8249
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3795 - accura

*Homework*

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer?

**solution**

In [19]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,500000]]))>0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!
Important note 1: Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.
Important note 2: Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns

precdict the test result

In [20]:
y_pred =ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm =confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1507   88]
 [ 188  217]]


0.862